social_book/social_book/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social_book_app.urls')),

]

social_book/social_book_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',views.register, name='register'),
    path('login/',views.login_view, name='login'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('authors-and-sellers/', views.authors_and_sellers, name='authors_and_sellers'),
    path('dummy/', views.dummy, name='dummy'),
    path('upload_books/', views.upload_books, name='upload_books'),
    path('uploaded_books/', views.uploaded_books, name='uploaded_books'),
           
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_book/social_book_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from .manager import CustomUserManager  
from django.core.validators import validate_email



class CustomUser(AbstractUser):
    email = models.EmailField(validators=[validate_email])
    public_visibility = models.BooleanField(default=True)
    age = models.PositiveIntegerField(null=True, blank=True)
    birth_year = models.PositiveIntegerField(null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)

    objects = CustomUserManager()

    def save(self, *args, **kwargs):
        if self.birth_year:
            current_year = timezone.now().year
            self.age = current_year - self.birth_year

        super().save(*args, **kwargs)


class UploadedFile(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=255)
    description = models.TextField()
    file = models.FileField(upload_to='uploads/')
    visibility = models.BooleanField(default=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    year_published = models.IntegerField()

    def __str__(self):
        return self.title

social_book/social_book_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from social_book_app.models import CustomUser
from .models import UploadedFile



class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    address = forms.CharField(max_length=255, required=True)
    birth_year = forms.IntegerField(required=True)
    public_visibility = forms.BooleanField(initial=True, required=False)

    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email', 'address', 'birth_year', 'public_visibility', 'password1', 'password2')

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.address = self.cleaned_data['address']
        user.birth_year = self.cleaned_data['birth_year']
        user.public_visibility = self.cleaned_data['public_visibility']

        if commit:
            user.save()

        return user


class UploadedFileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(UploadedFileForm, self).__init__(*args, **kwargs)

    class Meta:
        model = UploadedFile
        fields = ['title', 'description', 'file', 'visibility', 'cost', 'year_published']

    def save(self, commit=True):
        uploaded_file = super().save(commit=False)
        uploaded_file.user = self.user
        if commit:
            uploaded_file.save()
        return uploaded_file

social_book/social_book_app/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from social_book_app.models import CustomUser
from .models import UploadedFile
from .forms import UploadedFileForm


# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'login.html', {'success': "Registration successful. Please login."})
        else:
            error_message = form.errors.as_text()
            return render(request, 'register.html', {'error': error_message})
    return render(request, 'register.html')

def login_view(request):
    if request.method=="POST":
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect("/dashboard")
        else:
            return render(request, 'login.html', {'error': "Invalid credentials. Please try again."})

    return render(request, 'login.html')

@login_required
def dashboard(request):
    return render(request, 'dashboard.html', {'name': request.user.first_name})

def authors_and_sellers(request):
    users = CustomUser.objects.filter(public_visibility=True)
    return render(request, 'authors_and_sellers.html', {'users': users})

def dummy(request):
    return render(request, 'dummy.html')



def upload_books(request):
    if request.method == 'POST':
        form = UploadedFileForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            form.save()
            return render(request, 'dashboard.html', {'name': request.user.first_name})
    else:
        form = UploadedFileForm(user=request.user)

    return render(request, 'upload_books.html', {'form': form})

from django.contrib.auth.decorators import login_required

@login_required
def uploaded_books(request):
    uploaded_files = UploadedFile.objects.filter(user=request.user)
    return render(request, 'uploaded_books.html', {'uploaded_files': uploaded_files})

social_book/social_book_app/templates/authors_and_sellers.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Authors and Sellers</title>
        <link rel="stylesheet" href="{% static 'new.css' %}">
        <style>
            body{
                background-color: #f7f5f5;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h2>Authors and Sellers:</h2>
            <ol>
                {% for user in users %}
                <li style="font-family: 'Courier New', Courier, monospace;"><strong>{{ user.first_name }} {{ user.last_name }}  [{{ user.address }}]</strong></li>
                {% endfor %}
            </ol>
        </div>
        
    </body>

</html>

social_book/social_book_app/templates/dashboard.html
{% extends "dummy.html" %}
{% load static %}
<

  

{% block head %}
<style>
  .test {
  display: flex;
  flex-direction: row;
  
.card {
border: 1px solid #dadada;
box-shadow: 4px 4px 8px 0 rgba(0, 0, 0, 0.2);
transition: 0.2s;
width: 50%;
}

  }
</style>
  
{% endblock head %}

 
 

{% block body %}

<div class="test">

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Authors and sellers</h5>
    <!-- <h6 class="card-subtitle mb-2 text-body-secondary">Card subtitle</h6> -->
    <p class="card-text">This will show the users who ticked yes for profile visibility!</p>
    <a href="{% url 'authors_and_sellers' %}" class="card-link" style="color: #4caf50; text-decoration:none;">LIST</a>
  </div>
</div>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Upload Books</h5>
    <!-- <h6 class="card-subtitle mb-2 text-body-secondary">Card subtitle</h6> -->
    <p class="card-text">This will allow you to upload book in the pdf and jpeg formats!</p>
    <a href="{% url 'upload_books' %}" class="card-link" style="color: #4caf50; text-decoration:none;">UPLOAD</a>
  </div>
</div>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Uploaded Books</h5>
    <!-- <h6 class="card-subtitle mb-2 text-body-secondary">Card subtitle</h6> -->
    <p class="card-text">This will allow you to uploaded books by you!</p>
    <a href="{% url 'uploaded_books' %}" class="card-link" style="color: #4caf50; text-decoration:none;">VIEW</a>
  </div>
</div>
</div>
{% endblock body %}





<!-- visibility as check box shuold be in one line -->

social_book/social_book_app/templates/dummy.html
<!doctype html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title></title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block head %}
      
    {% endblock head %}
    </head>

    <body>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a style="font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;" class="navbar-brand" href="{% url 'dashboard' %}"><h1>Social Book</h1></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'authors_and_sellers' %}">Authors and Sellers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'upload_books' %}">Upload Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'uploaded_books' %}">Uploaded Books</a>
                </li>
        </div>
    </div>
    <a class="nav-item mr-3 nav-link p-3" href="{% url 'login' %}" style="background-color: #df0303">Logout</a>

</nav>
    {% block body %}
      
    {% endblock body %}
    </body>

</html>

social_book/social_book_app/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'new.css' %}">

    </head>

    <body>
        <div class="container">
            <div class="login form">
                <header><h2>Login</h2></header>
                <form action="{% url 'login' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" placeholder="Enter your email" name="email">
                    <input type="password" placeholder="Enter your password" name="password">
                    <input type="submit" class="button" value="Login">
                    <center>
                        {% if success %}
                        <p style="color: green;"><b>{{ success }}</b></p>
                        {% endif %}
                        {% if error %}
                        <p style="color: red;">{{ error }}</p>
                        {% endif %}
                    </center>
                </form>
                <div class="signup">
                    <span class="signup">Don't have an account?
                        <a href="{% url 'register' %}"><label for="check">Signup</label></a>
                    </span>
                </div>
            </div>
        </div>
    </body>

</html>

social_book/social_book_app/templates/register.html
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
            <link rel="stylesheet"  href="static/new.css">
    

    <body>
        <div class="container">
        <div class="registration form">
            <header><h2>Signup</h2></header>
            <form action="{% url 'register' %}" method="POST">
                {% csrf_token %}
            <div style="margin-top: 15px;">
                    <p>Public Visibility:</p>
                </div>
            <label class="toggle">
                <input type="radio" name="public_visibility" value="True" required> Yes
            </label>
            <label class="toggle">
                <input type="radio" name="public_visibility" value="False" required> No
            </label>
                <input type="text" placeholder="Enter your first name*" name="first_name">
                <input type="text" placeholder="Enter your last name" name="last_name">
                <input type="number" placeholder="Enter your birth year" name="birth_year">
                <input type="text" placeholder="Enter your address" name="address">
                <input type="text" placeholder="Enter your email" name="email">
                <input type="password" placeholder="Create a password" name="password1">
                <input type="password" placeholder="Confirm your password" name="password2">
                <input type="submit" class="button" value="Signup">
                <center>
                    {% if error %}
                    <p style="color: red;">{{ error }}</p>
                    {% endif %}
                </center>
        
            </form>
            <div class="signup">
                <span class="signup">Already have an account?
                    <a href="{% url 'login' %}"><label for="check">Signin</label></a>
                </span>
            </div>
        </div>
        </div>
    </body>
    </html>

    

social_book/social_book_app/templates/upload_books.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload Books</title>
    <style>
      
      body {
        font-family: 'Arial', sans-serif;
      }

      .container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
      }

      .form {
        width: 400px;
        padding: 20px;
        background-color: #f0f0f0;
        border-radius: 15px;
      }

      form {
        display: flex;
        flex-direction: column;
      }

      input,
      button {
        margin: 10px 0;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
      }

      button {
        background-color: #009579;
        color: white;
        cursor: pointer;
        border: none;
        border-radius: 4px;
      }

      button:hover {
        background-color: #3bceb3;
      }

      h2,
      h3 {
        text-align: center;
      }

      ul {
        list-style: none;
        padding: 0;
      }

      li {
        margin-bottom: 10px;
      }

    </style>
  </head>

  <body>
    <div class="container">
      <div class="form">
        <h2>Upload Books</h2>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <label for="id_title">Title:</label>
          <input type="text" name="title" required>
          <label for="id_description">Description:</label>
          <textarea name="description" required></textarea>
          <label for="id_file">File:</label>
          <input type="file" name="file" accept="application/pdf, image/jpeg" required>
          <label for="id_visibility">Visibility:</label>
          <input type="checkbox" id="visibility" name="visibility" checked>

          <label for="id_cost">Cost:</label>
          <input type="number" name="cost" step="0.01" min="0" value="0">
          <label for="id_year_published">Year of Published:</label>
          <input type="number" name="year_published" required>
          <button type="submit">Upload</button>
        </form>
      </div>
    </div>
  </body>

</html>

social_book/social_book_app/templates/uploaded_books.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Uploaded Books</title>
        <style>
            body {
                font-family: 'Arial', sans-serif;
            }

            .container {
                max-width: 800px;
                margin: 0 auto;
            }

            .file-item {
                margin-bottom: 20px;
                border: 1px solid #ccc;
                padding: 10px;
                border-radius: 5px;
            }

            h2 {
                text-align: center;
            }

        </style>
    </head>

    <body>
        <div class="container">
            <h2>Uploaded Books</h2>
            {% if uploaded_files %}
            {% for uploaded_file in uploaded_files %}
            <div class="file-item">
                <p><strong>Title:</strong> {{ uploaded_file.title }}</p>
                <p><strong>Description:</strong> {{ uploaded_file.description }}</p>
                <p><strong>File:</strong> <a href="{{ uploaded_file.file.url }}"
                        target="_blank">{{ uploaded_file.file.name }}</a></p>
                <p><strong>Visibility:</strong> {{ uploaded_file.visibility }}</p>
                <p><strong>Cost:</strong> {{ uploaded_file.cost }}</p>
                <p><strong>Year Published:</strong> {{ uploaded_file.year_published }}</p>
            </div>
            {% endfor %}
            {% else %}
            <p>No files uploaded yet.</p>
            {% endif %}
        </div>
    </body>

</html>